lga/urls.py
from django.urls import path
from . import views

app_name = 'lga'

urlpatterns = [
    path('lgalist', views.LgaList.as_view(), name = 'lga_list'),
    path('lgacreate', views.LgaCreate.as_view(), name = 'lga_create'),
    path('lgadetail/<int:pk>/', views.LgaDetail.as_view(), name = 'lga_detail'),
    path('lgadelete/<int:pk>/', views.LgaDelete.as_view(), name = 'lga_delete'),
    path('lgaupdate/<int:pk>/', views.LgaUpdate.as_view(), name = 'lga_update')
]

mda/urls.py
from django.urls import path
from . import views

app_name = 'mda'

urlpatterns = [
    path('ministrylist', views.MinistryList.as_view(), name = 'ministry_list'),
    path('ministrycreate', views.MinistryCreate.as_view(), name = 'ministry_create'),
    path('ministrydetail/<int:pk>/', views.MinistryDetail.as_view(), name = 'ministry_detail'),
    path('ministrydelete/<int:pk>/', views.MinistryDelete.as_view(), name = 'ministry_delete'),
    path('ministryupdate/<int:pk>/', views.MinistryUpdate.as_view(), name = 'ministry_update')
]

pmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('mda.urls')),
    path('', include('lga.urls')),
    path('', include('project.urls')),
    path('', include('pwa.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'project'

urlpatterns = [
    path('', views.landpage, name='landpage'),
    path('projectlist/', views.project_list, name='project_list'),
    path('years', views.YearList.as_view(), name='year_list'),
    path('year-detail/<int:pk>', views.YearDetail.as_view(), name='year_detail'),
    path('add-year', views.YearCreate.as_view(), name='year_create'),
    path('update-year/<int:pk>', views.YearUpdate.as_view(), name='year_update'),
    path('delete-year/<int:pk>', views.YearDelete.as_view(), name='year_delete'),
    #path('create-project', views.ProjectCreate.as_view(), name = 'project_create'),
    path('create-project', views.project_create, name='project_create'),
    path('project-detail/<int:pk>/',
         views.ProjectDetail.as_view(), name='project_detail'),
    path('project/<int:pk>/comment/', views.add_comment, name='comment_create'),
    path('project-delete/<int:pk>/',
         views.ProjectDelete.as_view(), name='project_delete'),
    path('pmp-project-update/<int:pk>/',
         views.PmpProjectUpdate.as_view(), name='pmp_project_update'),
    path('ministry-project-update/<int:pk>/',
         views.MinistryProjectUpdate.as_view(), name='ministry_project_update'),
    #path('pmp-projects', views.PmpProjects.as_view(), name='pmp_projects'),
    path('pmp-projects', views.pmp_project_list, name='pmp_projects'),
    #path('ministry-projects', views.MinistryProjects.as_view(), name='ministry_projects'),
    path('ministry-projects', views.ministry_project_list, name='ministry_projects'),
    #path('governor-projects', views.GovernorList.as_view(),name='governor_projects'),
    path('governor-projects', views.governor_project_list, name="governor_projects"),
    path('comment-detail/<int:pk>/',
         views.CommentDetail.as_view(), name='comment_detail'),
    path('comment/<int:pk>/delete', views.comment_delete, name='comment_delete'),
    path('comment-update/<int:pk>/',
         views.CommentUpdate.as_view(), name='comment_update'),
    path('pmp-reports', views.PmpReports.as_view(), name='pmp_reports'),
    path('ministry-reports', views.MinistryReports.as_view(),
         name='ministry_reports'),
    path('governor-reports', views.GovernorReports.as_view(),
         name='governor_reports'),
    path('add-report', views.ReportCreate.as_view(), name='create_report'),
    path('report/<int:pk>/', views.ReportDetail.as_view(), name='report_detail'),
    path('report-delete/<int:pk>/',
         views.ReportDelete.as_view(), name='report_delete'),
    path('report-update/<int:pk>/',
         views.ReportUpdate.as_view(), name='report_update'),
    path('dashboard/', views.dashboard, name='dashboard')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # USER URLS
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('change-password', views.change_password, name='change_password'),

    # ADHOC USERS URLS
    path('users/', views.user_list, name='user_list'),
    path('users/<int:id>/details/', views.user_details, name='user_details'),
    path('users/<int:id>/edit/', views.user_edit, name='user_edit'),
    path('users/addministryuser/', views.ministryuser_add, name='ministryuser_add'),
    path('users/addgovernor', views.governor_add, name='governor_add'),
    path('users/addpmp', views.pmp_add, name='pmp_add'),
    path('users/add-budget-user/', views.budget_add, name='budget_user_add'),
    path('users/add-due-process/', views.due_process_add, name='due_process_add'),
    path('users/<int:id>/delete/', views.user_delete, name='user_delete'),

    # service worker


]

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from mda.models import Ministry
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    is_ministryuser = models.BooleanField(default=False)
    is_governor = models.BooleanField(default=False)
    is_pmp = models.BooleanField(default=False)
    is_budget = models.BooleanField(default=False)
    is_dueprocess = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )

    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True)
    ministry = models.ForeignKey(
        Ministry, on_delete=models.CASCADE, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)

    def user_type(self):
        if self.is_ministryuser:
            return "Ministry Member"
        elif self.is_governor:
            return "Governor"
        elif self.is_pmp:
            return "PMP"
        elif self.is_budget:
            return "Budget Member"
        elif self.is_dueprocess:
            return "Due Process"
        else:
            return "Administrator"

    def fullname(self):
        return self.first_name + self.last_name

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.user_type


@receiver(post_save, sender=User)
def user_is_created(sender, instance, created, **kwargs):
    print(created)
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

users/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from users.forms import (
    MinistryUserForm,
    GovernorForm,
    PMPForm,
    BudgetForm,
    DueProcessForm,
    EditProfileForm
)
from users.models import Profile
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views import generic
from .forms import CustomUserCreationForm, CustomUserChangeForm
User = get_user_model()


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


@login_required
def profile(request):
    args = {'user': request.user}
    return render(request, 'registration/profile.html')


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'registration/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            update_session_auth_hash(request, form.user)
            form.save()
            return redirect('login')
        else:
            return redirect('change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'registration/change_password.html', args)


@login_required
def user_list(request):
    context = {}
    context['users'] = User.objects.all().order_by('-created')
    context['title'] = 'Users'
    return render(request, 'users/index.html', context)


@login_required
def user_details(request, id=None):
    context = {}
    context['user'] = get_object_or_404(User, id=id)
    return render(request, 'users/details.html', context)


# ministry user add
@login_required
def ministryuser_add(request):
    context = {}
    if request.method == 'POST':
        user_form = MinistryUserForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = MinistryUserForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)

# GOVERNOR ADD
@login_required
def governor_add(request):
    context = {}
    if request.method == 'POST':
        user_form = GovernorForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = GovernorForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


# PMP ADD
@login_required
def pmp_add(request):
    context = {}
    if request.method == 'POST':
        user_form = PMPForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = PMPForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


# Budget & eco planning ADD
@login_required
def budget_add(request):
    context = {}
    if request.method == 'POST':
        user_form = BudgetForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = BudgetForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


# due process ADD
@login_required
def due_process_add(request):
    context = {}
    if request.method == 'POST':
        user_form = DueProcessForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = DueProcessForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


@login_required
def user_edit(request, id=None):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        user_form = MinistryUserForm(
            request.POST, request.FILES, instance=user)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/edit.html', {'user_form': user_form})
    else:
        user_form = MinistryUserForm(instance=user)
        return render(request, 'users/edit.html', {'user_form': user_form})


@login_required
def user_delete(request, id=None):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        user.delete()
        return HttpResponseRedirect(reverse('users:user_list'))
    else:
        context = {}
        context['user'] = user
        return render(request, 'users/delete.html', context)

users/templates/accounts_base.html
<!-- load pwa -->

{% load staticfiles %}
<html>
<head>
    <!--progressive_web_app_meta -->

<title>Mu Taru Mu Gyara</title>

<!--Meta tags-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Add to home screen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="MTMG PWA">
  <link rel="apple-touch-icon" href="images/icons/icon-152x152.png">
  <meta name="msapplication-TileImage" content="images/icons/icon-144x144.png">
  <meta name="msapplication-TileColor" content="#2F3BA2">
  <!--Meta ends -->

<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>

<!--dropdown style-->
<style>
.dropbtn {
    border: none;
    cursor: pointer;
}


.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    overflow: auto;
}

.dropdown-content a {
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}


.show {display:block;}
</style>

<!--end dropdown style-->

</head>
<body>
<!--HEADERT-->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
    <span class="brand" id="header-link"><strong><a class="head-link" href="{% url 'project:project_list' %}">Mu taru mu gyara</a><strong></span>
  
  </div>
</nav>

  <div class="container">
  {% block content %}
  {% endblock %}
</body>
</html>

users/templates/base.html
<!-- load pwa -->

{% load staticfiles %}
<html>
<head>
    <!--progressive_web_app_meta -->

<title>Mu Taru Mu Gyara</title>

<!--Meta tags-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Add to home screen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="MTMG PWA">
  <link rel="apple-touch-icon" href="images/icons/icon-152x152.png">
  <meta name="msapplication-TileImage" content="images/icons/icon-144x144.png">
  <meta name="msapplication-TileColor" content="#2F3BA2">
  <!--Meta ends -->

<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/base.css' %}"/>
 <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"><!--add new user drop down-->


<!--dropdown style-->
<style>
.dropbtn {
    border: none;
    cursor: pointer;
}


.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    overflow: auto;
}

.dropdown-content a {
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}


.show {display:block;}

.affix {
    position:fixed;
    padding-bottom: 100%;
}

.topf {
  
}

.navbar-inverse {
  background-color:green;
  margin-bottom: -60px;
}

body {

}

</style>

<!--end dropdown style-->

</head>
<body>
<!--HEADERT-->
<!-- <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
    <span style="font-size:25px;cursor:pointer;margin-left:10px;" onclick="openNav()"id="header-link">☰</span>
    <span class="brand" id="header-link"><strong><a class="head-link" href="{% url 'project:project_list' %}">Mu taru mu gyara</a><strong></span>
    

  
  </div>
</nav> -->
<!--HEADER ENDS-->

<!-- new nav -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'project:project_list' %}">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'project:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:project_create' %}"><i class="fas fa-edit"></i>Need</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:create_report' %}"><i class="fas fa-comment"></i>Comment</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:year_list' %}"><i class="fas fa-clock"></i> Budget Year</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:pmp_projects' %}"><i class="fas fa-building"></i>Projects</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:ministry_projects' %}"><i class="fas fa-building"></i>Projects</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:governor_projects' %}"><i class="fas fa-building"></i>Projects</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:pmp_reports' %}"><i class="fas comment-alt"></i>Reports</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'project:governor_reports' %}"><i class="fas comment-alt"></i>Reports</a></li>
            <li role="separator" class="divider"></li>
            <li class="btn btn-info">MDA's</li>
            <li><a href="{% url 'mda:ministry_list' %}"><i class="fas fa-landmark"></i> Ministries</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><i class="fas fa-landmark"></i> Assembly</a></li>
            <li><a href="{% url 'mda:ministry_list' %}"><i class="fas fa-landmark"></i> Ministries</a></li>
            <li><a href="{% url 'lga:lga_list' %}"><i class="fas fa-layer-group"></i> LGA</a></li>
            <li><a href="{% url 'users:user_list' %}"><i class="fas fa-users"></i> Users</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile' %}"><i class="fas fa-user"></i>Profile</a></li>
            <li><a href="{% url 'logout'%}"><i class="fas fa-sign-out-alt"></i>Logout</a></li>
            {% else %}
            <li><a href="{% url 'login'%}"><i class="fas fa-sign-in-alt"></i>Login</a></li>
            {% endif %}
            <li role="separator" class="divider"></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- new nav -->

<!--SIDEBAR-->
<!-- <aside id="mySidenav" class="sidenav">
   {% if user.is_authenticated %}
    <a href="{% url 'project:dashboard' %}"><i class="fas fa-tachometer-alt"></i> Dashboard</a>	
    <hr>
    {% endif %}

{% if not user.is_authenticated %}
  <a href="{% url 'project:project_create' %}"><i class="fas fa-edit"></i> Need</a>	
  <hr>	
  <a href="{% url 'project:create_report' %}"><i class="fas fa-comment"></i> Comment</a>		
  <hr>
  {% endif %}


  {% if user.is_authenticated %}
  {% if user.is_pmp or user.is_superuser  %}
    <a href="{% url 'project:year_list' %}"><i class="fas fa-clock"></i> Budget Year</a>		
  <hr>
  <a href="{% url 'project:pmp_projects' %}"><i class="fas fa-building"></i> Projects</a>
  <hr>	
  {% endif %}
  

  {% if user.is_ministryuser or user.is_superuser %}
  <a href="{% url 'project:ministry_projects' %}"><i class="fas fa-building"></i> Projects</a>
<hr>
  {% endif %}

  {% if user.is_governor or user.is_superuser %}
  <a href="{% url 'project:governor_projects' %}"><i class="fas fa-building"></i> Projects</a>	
  <hr>
  <a href="{% url 'project:pmp_projects' %}"><i class="fas fa-building"></i> All Projects</a>
  <hr>
  {% endif %}

  {% if user.is_pmp or user.is_superuser %}
  <a href="{% url 'project:pmp_reports' %}"><i class="fas fa-comment-alt"></i> Reports</a>	
  <hr>
  {% endif %}

{% if user.is_ministryuser or user.is_superuser %}
  <a href="{% url 'project:ministry_reports' %}"><i class="fas fa-comment-alt"></i> Reports</a>
  <hr>
  {% endif %}

{% if user.is_governor or user.is_superuser %}
<a href="{% url 'project:governor_reports' %}"><i class="fas fa-comment-alt"></i> Reports</a>
<hr>
{% endif %}

{% if user.is_pmp or user.is_superuser %}
<a href="#categorySubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-landmark"></i> MDA's</a>
  <ul class="collapse list-unstyled" id="categorySubmenu">
  <hr>
   <li>
  <a href="{% url 'mda:ministry_list' %}"><i class="fas fa-landmark"></i> Ministries</a>
  </li> -->

 <!-- <li>
<a href="#"><i class="fas fa-landmark"></i> Assembly</a>
  </li> -->
  <!-- </ul> -->
  <hr>
<!-- 

  <a href="{% url 'lga:lga_list' %}"><i class="fas fa-layer-group"></i> LGA</a>
  <hr>
  <a href="{% url 'users:user_list' %}"><i class="fas fa-users"></i> Users</a>
  <hr>
  {% endif %}
  

  <a href="{% url 'users:profile' %}"><i class="fas fa-user"></i> Profile</a>
  <hr>
  {% endif %}


  {% if user.is_authenticated %}
  <a href="{% url 'logout'%}"><i class="fas fa-sign-out-alt"></i> Logout</a>
  {% else %}
  <a href="{% url 'login'%}"><i class="fas fa-sign-in-alt"></i> Login</a>
  {% endif %}
  <hr>
</aside> -->
<!--SIDEBAR ENDS-->
  <div class="container">
  {% block content %}
  {% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- DataTables js-->
        <script src="//code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
        <script src="//cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
        <!--datatables initialization-->

 <script>
            $(document).ready(function() {
                $('#example').DataTable({
                    dom: 'Bfrtip',
                    buttons: [{
                        extend: 'excelHtml5',
                        exportOptions: {
                            columns: ':visible(export-col)'
                        }
                    }, 
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible(export-col)'
                        }
                    }, 
                     ]
                });
            });
        </script>


<!--dropdown script-->
<script>
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

<!--end dropdown script-->

</body>
</html>