lga/urls.py
from django.urls import path
from . import views

app_name = 'lga'

urlpatterns = [
    path('lgalist', views.LgaList.as_view(), name = 'lga_list'),
    path('lgacreate', views.LgaCreate.as_view(), name = 'lga_create'),
    path('lgadetail/<int:pk>/', views.LgaDetail.as_view(), name = 'lga_detail'),
    path('lgadelete/<int:pk>/', views.LgaDelete.as_view(), name = 'lga_delete'),
    path('lgaupdate/<int:pk>/', views.LgaUpdate.as_view(), name = 'lga_update')
]

pmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('mda.urls')),
    path('', include('lga.urls')),
    path('', include('project.urls')),
    path('', include('pwa.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lga/models.py
from django.db import models
from django.urls import reverse

class Lga(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("lga_detail", kwargs={"pk": self.pk})

    def lgaProjectCount(self):
        return self.projects.all().count()

lga/forms.py
from django import forms
from lga.models import Lga

class LgaForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Name'
        }
    ))
    class Meta:
        model = Lga
        fields = '__all__'

lga/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView 
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from lga.forms import LgaForm
from lga.models import Lga 


class LgaCreate(LoginRequiredMixin, CreateView):
    model = Lga
    form_class = LgaForm
    success_url = reverse_lazy('lga:lga_list')


class LgaDetail(LoginRequiredMixin, DetailView):
    model = Lga
    
class LgaList(LoginRequiredMixin, ListView):
    model = Lga 

class LgaDelete(LoginRequiredMixin, DeleteView):
    model = Lga
    success_url = reverse_lazy('lga:lga_list')

class LgaUpdate(LoginRequiredMixin, UpdateView):
    model = Lga
    form_class = LgaForm
    success_url = reverse_lazy('lga:lga_list')

lga/templates/lga/lga_confirm_delete.html
{% extends 'base.html' %}{% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">

    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h3>Delete LGA</h3>
        </div>
        <div class="panel-body">

            <div class="container-fluid">

                <form method="post">{% csrf_token %}
                <h4> Are you sure you want to delete "{{ object }}" ? </h4><br>
                    <input type="submit" class="btn btn-danger btn-lg" value="Yes! Delete" />
                </form>
                {% endblock %}

lga/templates/lga/lga_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
<div class="panel panel-inverse">
<div class="panel-heading">
<h3>LGA Detail</h3>
</div>
<div class="panel-body">
<h4>Name:   {{lga.name}}</h4>
<h4>Projects:  {{lga.lgaProjectCount}}</h4>
<a class="btn btn-info btn-lg" href="{% url 'lga:lga_update' lga.id %}">Edit</a>
<a class="btn btn-danger btn-lg" href="{% url 'lga:lga_delete' lga.id %}">Delete</a>
<br><br>
<div class="panel panel-default">
                <div class="panel-heading">
                    <h5><b>Projects</b></h5>
                </div>
                <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th>S/N</th>
                                <th>Title</th>
                                <th>Description</th> 
                                <th>Submitted by</th>
                                 <th>Date</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for project in lga.projects.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{project.title}}</td>
                                <td>{{project.description}}</td>
                                <td>{{project.submitted_by}}</td>
                                <td>{{project.date}}</td>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</div>
</div>
</div>
{% endblock content %}

lga/templates/lga/lga_form.html
{% extends "base.html" %}
{% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
<div class="panel panel-inverse">
<div class="panel-heading">
<h3>LGA Form</h3>
</div>
<div class="panel-body">
<form method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Add" class="btn btn-primary btn-lg">
</form>
</div>
</div>
{% endblock content %}

lga/templates/lga/lga_list.html
{% extends "base.html" %}
{% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
<div class="panel panel-inverse">
<div class="panel-heading">
<h3>List of LGA's<span><a class="btn btn-primary btn-lg" href="{% url 'lga:lga_create' %}" style="float:right; margin-top:-10px;">Add new</a></span></h3>
</div>
<hr>
<div class="panel-body">
  <div class="table-responsive table-bordered">          
<table class="table table-bordered table-striped table-condensed">
<thead>
<tr>
<th>S/N</th>
<th>Name</th>
<th>Projects</th>
</tr>
</thead>
{% for lga in object_list %}

<tbody>
<tr>
<td>{{forloop.counter}}</td>
<td><a href="{% url 'lga:lga_detail' lga.id %}">{{lga.name}}</a></td>
<td>{{lga.lgaProjectCount}}</td>
</tr>
{% endfor %}
</tbody>
</div>
</div></div>
{% endblock content %}