lga/urls.py
from django.urls import path
from . import views

app_name = 'lga'

urlpatterns = [
    path('lgalist', views.LgaList.as_view(), name = 'lga_list'),
    path('lgacreate', views.LgaCreate.as_view(), name = 'lga_create'),
    path('lgadetail/<int:pk>/', views.LgaDetail.as_view(), name = 'lga_detail'),
    path('lgadelete/<int:pk>/', views.LgaDelete.as_view(), name = 'lga_delete'),
    path('lgaupdate/<int:pk>/', views.LgaUpdate.as_view(), name = 'lga_update')
]

pmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('mda.urls')),
    path('', include('lga.urls')),
    path('', include('project.urls')),
    path('', include('pwa.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'project'

urlpatterns = [
    path('', views.landpage, name='landpage'),
    path('projectlist/', views.project_list, name='project_list'),
    path('years', views.YearList.as_view(), name='year_list'),
    path('year-detail/<int:pk>', views.YearDetail.as_view(), name='year_detail'),
    path('add-year', views.YearCreate.as_view(), name='year_create'),
    path('update-year/<int:pk>', views.YearUpdate.as_view(), name='year_update'),
    path('delete-year/<int:pk>', views.YearDelete.as_view(), name='year_delete'),
    #path('create-project', views.ProjectCreate.as_view(), name = 'project_create'),
    path('create-project', views.project_create, name='project_create'),
    path('project-detail/<int:pk>/',
         views.ProjectDetail.as_view(), name='project_detail'),
    path('project/<int:pk>/comment/', views.add_comment, name='comment_create'),
    path('project-delete/<int:pk>/',
         views.ProjectDelete.as_view(), name='project_delete'),
    path('pmp-project-update/<int:pk>/',
         views.PmpProjectUpdate.as_view(), name='pmp_project_update'),
    path('ministry-project-update/<int:pk>/',
         views.MinistryProjectUpdate.as_view(), name='ministry_project_update'),
    #path('pmp-projects', views.PmpProjects.as_view(), name='pmp_projects'),
    path('pmp-projects', views.pmp_project_list, name='pmp_projects'),
    #path('ministry-projects', views.MinistryProjects.as_view(), name='ministry_projects'),
    path('ministry-projects', views.ministry_project_list, name='ministry_projects'),
    #path('governor-projects', views.GovernorList.as_view(),name='governor_projects'),
    path('governor-projects', views.governor_project_list, name="governor_projects"),
    path('comment-detail/<int:pk>/',
         views.CommentDetail.as_view(), name='comment_detail'),
    path('comment/<int:pk>/delete', views.comment_delete, name='comment_delete'),
    path('comment-update/<int:pk>/',
         views.CommentUpdate.as_view(), name='comment_update'),
    path('pmp-reports', views.PmpReports.as_view(), name='pmp_reports'),
    path('ministry-reports', views.MinistryReports.as_view(),
         name='ministry_reports'),
    path('governor-reports', views.GovernorReports.as_view(),
         name='governor_reports'),
    path('add-report', views.ReportCreate.as_view(), name='create_report'),
    path('report/<int:pk>/', views.ReportDetail.as_view(), name='report_detail'),
    path('report-delete/<int:pk>/',
         views.ReportDelete.as_view(), name='report_delete'),
    path('report-update/<int:pk>/',
         views.ReportUpdate.as_view(), name='report_update'),
    path('dashboard/', views.dashboard, name='dashboard')
]

project/models.py
from django.db import models
from django.utils import timezone
from lga.models import Lga
from mda.models import Ministry
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
User = get_user_model()


class Year(models.Model):
    year = models.CharField(max_length=4)
    description = models.TextField()
    date_open = models.DateField(blank=True, null=True)
    date_closed = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.year

    def yearProjectCount(self):
        return self.projects.all().count()

    


class Project(models.Model):
    title = models.CharField(max_length = 250)
    description = models.TextField()
    lga = models.ForeignKey(Lga, on_delete=models.CASCADE, related_name='projects')
    ministry = models.ForeignKey(Ministry, on_delete=models.CASCADE, related_name='projects')
    date = models.DateField(default=timezone.now)
    

    unreviewed = 'unreviewed'
    approved = 'approved'
    disapproved = 'disapproved'


    STATUS_CHOICES = (
        (unreviewed,'unreviewed'),
        (approved,'approved'),
        (disapproved,'disapproved')
    )

    status = models.CharField(max_length = 15, choices = STATUS_CHOICES, default = unreviewed)
    progress = models.CharField(max_length = 3, default=0, verbose_name="progress(%)")
    progress_comment = models.TextField(default="none", blank=True)    
    submittedBy = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    budget_year = models.ForeignKey(Year, on_delete=models.CASCADE, blank=True, null=True, related_name='projects')

    
    
    def __str__(self):
        return self.title

    def projectCommentCount(self):
        return self.comments.all().count()

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'All Projects'
       # ordering = ['-date']



class Comment(models.Model):
    text = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name = 'comments')
    picture = models.ImageField(upload_to='media/comments/%y/%m/%d', blank = True, verbose_name='image')
    created = models.DateField(default=timezone.now)
    submittedBy = models.CharField(max_length = 100, verbose_name = 'Full Name', blank=True, null=True)    

    unreviewed = 'unreviewed'
    approved = 'approved'
    disapproved = 'disapproved'


    STATUS_CHOICES = (
        (unreviewed,'unreviewed'),
        (approved,'approved'),
        (disapproved,'disapproved')
    )
    status = models.CharField(max_length = 15, choices = STATUS_CHOICES, default = unreviewed)


    class Meta:
       # ordering = ['-created']
        verbose_name = 'Comment'
        verbose_name_plural = '.Comments'


    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("comment_detail", kwargs={"pk": self.pk})


class UnreviewedComment(Comment):
    class Meta:
        proxy = True
        verbose_name = 'Unreviewed Comment'
        verbose_name_plural = '.Unreviewed Comments'
    
   
class ApprovedComment(Comment):
    class Meta:
        proxy = True
        verbose_name = 'Approved Comment'
        verbose_name_plural = '.Approved Comments'


class DisapprovedComment(Comment):
    class Meta:
        proxy = True
        verbose_name = 'Disapproved Comment'
        verbose_name_plural = '.Disapproved Comments'

    

    
    

# Report for no project in list

class Report(models.Model):
     text = models.TextField()
     report_title = models.CharField(max_length = 200, verbose_name="title", blank=True, null=True)
     picture = models.ImageField(upload_to='media/reports/%y/%m/%d', blank = True, verbose_name='image')
     lga = models.ForeignKey(Lga, on_delete=models.CASCADE, blank=True, null=True)
     ministry = models.ForeignKey(Ministry, on_delete=models.CASCADE, null = True)
     submittedBy = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='users')

    
     unreviewed = 'unreviewed'
     approved = 'approved'
     disapproved = 'disapproved'


     STATUS_CHOICES = (
        (unreviewed,'unreviewed'),
        (approved,'approved'),
        (disapproved,'disapproved')
    )
     status = models.CharField(max_length = 15, choices = STATUS_CHOICES, default = unreviewed)
     created = models.DateField(default=timezone.now)
     
     class Meta:
        ordering = ['-created']
        verbose_name = 'Report'
        verbose_name_plural = 'Reports'
        
     def __str__(self):
        return self.text

     def get_absolute_url(self):
        return reverse("report_detail", kwargs={"pk": self.pk})
    

    
     
class UnreviewedReport(Report):
    class Meta:
        proxy = True
        verbose_name = 'Unreviewed Report'
        verbose_name_plural = 'Unreviewed Reports'
    
   
class ApprovedReport(Report):
    class Meta:
        proxy = True
        verbose_name = 'Approved Report'
        verbose_name_plural = 'Approved Reports'


class DisapprovedReport(Report):
    class Meta:
        proxy = True
        verbose_name = 'Disapproved Report'
        verbose_name_plural = 'Disapproved Reports'

project/forms.py
from django import forms
from django.db import transaction
from project.models import Project, Comment, Report, Year
from lga.models import Lga
from mda.models import Ministry
from lga.models import Lga


class YearForm(forms.ModelForm):

    year = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Budget Year'
        }
    ))

    description = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    date_open = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'yyyy-mm-dd'
        }
    ))

    date_closed = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'yyyy-mm-dd'
        }
    ))

    class Meta:
        model = Year
        fields = '__all__'


class ProjectForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Title your need'
        }
    ))

    description = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    lga = forms.ModelChoiceField(queryset=Lga.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    ministry = forms.ModelChoiceField(queryset=Ministry.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

  

    class Meta:
        model = Project
        fields = ('title', 'description', 'lga',
                  'ministry')


class FilterForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))

    lga = forms.ModelChoiceField(queryset=Lga.objects.all(), required=False, widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    ministry = forms.ModelChoiceField(queryset=Ministry.objects.all(), required=False, widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    date = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))

    class Meta:
        model = Project
        fields = ('title', 'lga', 'ministry', 'date')


class PmpProjectEditForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Title your need'
        }
    ))

    description = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    lga = forms.ModelChoiceField(queryset=Lga.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    ministry = forms.ModelChoiceField(queryset=Ministry.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    submittedBy = forms.CharField(label="Full Name", widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter your name'
        }
    ))

    progress_comment = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'enter your phone number'
        }
    ))

    class Meta:
        model = Project
        exclude = ('date', 'budget_year')


class ProjectFilterForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('date',)


class MinistryProjectEditForm(forms.ModelForm):
    progress_comment = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control'
        }
    ))

    class Meta:
        model = Project
        fields = ['progress', 'progress_comment']


class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Comment'
        }
    ))

    picture = forms.ImageField()

    class Meta:
        model = Comment
        fields = ['text', 'picture']

    def post_comment(self):
        text = self.cleaned_data.get('text')
        picture = self.cleaned_data.get('picture')


class CommentEditForm(forms.ModelForm):

    text = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Comment'
        }
    ))

    picture = forms.ImageField()

    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'enter your phone number'
        }
    ))

    class Meta:
        model = Comment
        fields = ['text', 'picture', 'phone', 'status']


# report form

class ReportForm(forms.ModelForm):
    report_title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Title your report'
        }
    ))

    text = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Comment'
        }
    ))

    lga = forms.ModelChoiceField(queryset=Lga.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    ministry = forms.ModelChoiceField(queryset=Ministry.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    picture = forms.ImageField()


    class Meta:
        model = Report
        fields = ['report_title', 'text', 'lga', 'ministry',
                  'picture']


class ReportEditForm(forms.ModelForm):

    report_title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter report Title'
        }
    ))

    text = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Comment'
        }
    ))

    lga = forms.ModelChoiceField(queryset=Lga.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    ministry = forms.ModelChoiceField(queryset=Ministry.objects.all(), widget=forms.Select(
        attrs={
            'class': 'form-control'
        }
    ))

    picture = forms.ImageField()

    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'enter your phone number'
        }
    ))

    class Meta:
        model = Report
        fields = ['report_title', 'text', 'lga', 'ministry',
                  'picture', 'phone', 'status']

project/templates/project/governor_projects.html
{% extends "base.html" %}
{% block content %}

<form method="get" class="form-inline">
<label for="id_created_min">From</label> <input type="text" name="created_min" id="id_created_min" placeholder="yyyy-mm-dd" class="form-control">
<label for="id_created_max">To</label> <input type="text" name="created_max" id="id_created_max" placeholder="yyyy-mm-dd"  class="form-control">
    <button type="submit" class="btn btn-success">Search</button>&nbsp;<a href="{% url 'project:governor_projects' %}" class="btn btn-info">Refresh</a>
  </form>


<div class="col-sm-12 col-md-12">
    <div class="panel panel-default">
    <div class="panel-heading">
            <h5><strong>Project</strong></h5>
            </div>
                    <div class="panel-body">
        <div class="table-responsive">
                <table class="table table-bordered table-condensed" id="example">
                    <thead>
                        <tr><th>S/N</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Ministry</th>
                            <th>LGA</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Submitted By</th>
                            <th>Phone No.</th>
                        </tr>
                    </thead>
                    <tbody>
 {% for project in filter.qs %}                        <tr>
                        <td>{{forloop.counter}}</td>
                            <td><a href="{% url 'project:project_detail' project.id %}">{{project.title}}</a></td>
                            <td>{{project.description|truncatewords:"8"}}</td>
                            <td>{{project.ministry}}</td>
                            <td>{{project.lga}}</td>
                            <td>{{project.date}}</td>
                            <td>{{project.status}}</td>
                            <td>{{project.submitted_by}}</td>
                            <td>{{project.phone}}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
        </div>
</div>{% endblock %}

project/templates/project/ministry_projects.html
{% extends "base.html" %}
{% block content %}

<form method="get" class="form-inline">
<label for="id_created_min">From</label> <input type="text" name="created_min" id="id_created_min" placeholder="yyyy-mm-dd" class="form-control">
<label for="id_created_max">To</label> <input type="text" name="created_max" id="id_created_max" placeholder="yyyy-mm-dd"  class="form-control">
    <button type="submit" class="btn btn-success">Search</button>&nbsp;<a href="{% url 'project:ministry_projects' %}" class="btn btn-info">Refresh</a>
  </form>

<div class="col-sm-12 col-md-12">
    <div class="panel panel-default">
    <div class="panel-heading">
            <h5><strong>Projects</strong></h5>
            </div>
                    <div class="panel-body">
<div class="table-responsive">
                <table class="table table-bordered table-condensed" id="example">
                    <thead>
                        <tr><th>S/N</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Ministry</th>
                            <th>LGA</th>
                            <th>Date</th>
                            <th>progress</th>
                            <th>status</th>
                            <th>Submitted By</th>
                            <th>Phone No.</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in filter.qs %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                            <td><a href="{% url 'project:project_detail' project.id %}">{{project.title}}</a></td>
                            <td>{{project.description|truncatewords:"8"}}</td>
                            <td>{{project.ministry}}</td>
                            <td>{{project.lga}}</td>
                            <td>{{project.date}}</td>
                            <td>{{project.progress}}%</td>
                            <td>{{project.status}}</td>
                            <td>{{project.submitted_by}}</td>
                            <td>{{project.phone}}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
        </div>
</div>{% endblock %}

project/templates/project/pmp_projects.html
{% extends "base.html" %}
{% block content %}

<form method="get" class="form-inline">
<label for="id_created_min">From</label> <input type="text" name="created_min" id="id_created_min" placeholder="yyyy-mm-dd" class="form-control">
<label for="id_created_max">To</label> <input type="text" name="created_max" id="id_created_max" placeholder="yyyy-mm-dd"  class="form-control">
    <button type="submit" class="btn btn-success">Search</button>&nbsp;<a href="{% url 'project:pmp_projects' %}" class="btn btn-info">Refresh</a>
  </form>
   <div class="panel panel-default">
    <div class="panel-heading">
            <h5><strong>Projects</strong></h5>
            </div>
                    <div class="panel-body">
<div class="table-responsive">
                <table class="table table-bordered table-condensed" id="example">
                    <thead>
                        <tr><th>S/N</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Ministry</th>
                            <th>LGA</th>
                            <th>Date</th>
                            <th>Progress</th>
                            <th>Status</th>
                            <th>Submitted By</th>
                            <th>Phone No.</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in filter.qs %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                            <td><a href="{% url 'project:project_detail' project.id %}">{{project.title}}</a></td>
                            <td>{{project.description|truncatewords:"8"}}</td>
                            <td>{{project.ministry}}</td>
                            <td>{{project.lga}}</td>
                            <td>{{project.date}}</td>
                            <td>{{project.progress}}%</td>
                            <td>{{project.status}}</td>
                            <td>{{project.submittedBy}}</td>
                            <td>{{project.submittedBy.phone}}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
        </div>
</div>{% endblock %}

project/templates/project/project_confirm_delete.html
{% extends 'base.html' %}{% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">

    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h3>Delete Project</h3>
        </div>
        <div class="panel-body">

            <div class="container-fluid">

                <form method="post">{% csrf_token %}
                <h4> Are you sure you want to delete "{{ object }}" ? </h4><br>
                    <input type="submit" class="btn btn-danger btn-lg" value="Yes! Delete" />
                </form>
                {% endblock %}

project/templates/project/project_detail.html
{% extends 'base.html' %} {% block content %}
<div class="col-sm-12 col-md-12">
    <div class="panel panel-default">
    <div class="panel-heading">
                <h5><strong>Project: {{project.title}}</strong></h5>
                </div>
        <div class="panel-body">
            <p>Description: {{project.description}}</p>
            <p>Ministry: {{project.ministry}}</p>
            <p>LGA: {{project.lga}}</p>
            <p>Date Submitted: {{project.date}}</p>
            <p>Status: {{project.status}}</p>
            <p>Progress: {{project.progress}}%</p>
            <p>Budget Year: {{project.budget_year}}</p>
            {% if not user.is_authenticated %}
            <p>Status: {{project.status}}</p>
            <div class="alert alert-info" role="alert">
            use your phone number as your tracking code, to check status of your need
            </div>
            {% endif %}

            {% if user.is_authenticated %}
            {% if user.is_pmp or user.is_superuser %}
            <a class="btn btn-danger" href="{% url 'project:project_delete' project.id %}">Delete</a>
            <a class="btn btn-info" href="{% url 'project:pmp_project_update' project.id %}">Update</a>
            {% endif %}


            {% if user.is_ministryuser or user.is_superuser %}
            <a class="btn btn-info" href="{% url 'project:ministry_project_update' project.id %}">Update</a>
            {% endif %}
            {% endif %}

        </div>
    </div>
</div>
</div>

{% if  user.is_authenticated %}
<div class="col-sm-12 col-md-12">
<div class="panel panel-default">
<div class="panel-heading">
<h5><strong>Comments ({{project.projectCommentCount}})</strong></h5>
</div>
<div class="panel-body">

<div class="table-responsive">
                <table class="table table-bordered table-condensed" id="table_id">
                    <thead>
                        <tr><th>S/N</th>
                            <th>Text</th>
                            <th>Created</th>
                            <th>Submitted By</th>
                            <th>Phone No.</th>
                            <th>Status</th>
                            <th>image</th>
                       </tr>
                    </thead>
                    <tbody>
                        {% for comment in project.comments.all %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                            <td><a href="{% url 'project:comment_detail' comment.id %}">{{comment.text|truncatewords:"8"}}</a></td>
                           <td>{{comment.created}}</td>
                            <td>{{comment.submittedBy}}</td>
                            <td>{{comment.submittedBy.phone}}</td>
                            <td>{{comment.status}}</td>
                            <td><a href="/media/{{comment.picture}}">Image</a></td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
       </div>
</div>
</div>
</div>
{% endif %}
{% endblock %}

project/templates/project/project_form.html
{% extends 'base.html' %} {% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-body">
{% if difference.days <= 0 %}
<h1> Submittion of need is Closed</h1>
{% else %}
            <form method="POST">
                {% csrf_token %} {{form.as_p}}
                <input type="submit" value="submit" class="btn btn-primary btn-lg">
            </form>
{% endif %}
        </div>
    </div>
</div>
{% endblock %}

project/templates/project/project_list.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<div class="row">
  <div class="col-sm-2 col-md-2">
    <div class="thumbnail affix d-md-none .d-lg-block">
      <div class="caption">
        <h3>Profile Details</h3>
        <img src = "{% static 'img/ava.png' %}" width ="170px" heigth = "400px" class = "img-responsive"/>
      </div>
      Fullname: <span class = "badge badge-success">12</span><br><br>
      Email: <span class = "badge badge-success">12</span><br><br>
      Phone Number: <span class = "badge badge-success">12</span><br><br>
      <p><a href="#" class="btn btn-lg btn-primary" role="button">View</a></p>
    </div>
  </div>
<div class="col-sm-12 col-md-8">
    <div class="panel panel-default">
        <div class="panel-body">
            <form action="" method="get" role="form">
                <div class="form-group">
                Tracking code:<input type="text" placeholder="your phone number" name="phone" id="id_title" class="form-control">
                </div> 
                <div class="form-group">
                Title:<input type="text" placeholder="project title" name="title" id="id_title" class="form-control">
                </div>   
                <div class="form-group">
                LGA:<select class="form-control" name="lga" id="id_lga" value={{form.lga}}
                </div>
                <div class="form-group">
                Ministry: <select class=" form-control " name="ministry " id="id_ministry " value={{form.ministry}}
                </div>
                <div class="form-group">
                Date:<input class="form-control" placeholder="yyyy-mm-dd" type="text" name="date"
                    id="id_date">
                    </div>
                <button class="btn btn-success" type="submit"><i class="fas fa-search"></i> search</button>
            </form>

            <hr>

        </div>
    </div>
</div>
  <div class="col-sm-2 col-md-2">
    <div class="thumbnail affix d-md-none .d-lg-block">
      <div class="caption">
        <h3>My submission statistics</h3>
        <img src = "{% static 'img/stat.jpg' %}" width ="170px" heigth = "400px" class = "img-responsive"/>
      </div>
      Needs: <span class = "badge badge-success">12</span><br><br>
      Comments: <span class = "badge badge-success">12</span><br><br>
      Reports: <span class = "badge badge-success">12</span><br><br>
      Needs: <span class = "badge badge-success">12</span><br><br><br>
      <p><a href="#" class="btn btn-lg btn-primary" role="button">View All</a></p>
    </div>
  </div>
  
</div>

 <div class = "row">
    <div class = "col-md-2"></div>
    
      <div class="col-md-8">
      {% for project in filter.qs %}
    

    <div class="panel panel-default">
    <div class="panel-heading">
            <h4><strong>{{project.title}}</strong><span style="font-size:15px;"> - {{project.date}}</span></h4>
    </div>
        <div class="panel-body">

            <h3>{{project.description}}</h3>
            <h5><i class="fas fa-landmark"></i> {{project.ministry}}</h5>
            <h5><i class="fas fa-map-marked-alt"></i> {{project.lga}}</h5>
            <a href="{% url 'project:comment_create' project.id %}" class="btn btn-primary"><i class="fas fa-comment"></i> Comment</a>
        </div>
    </div>
    {% endfor %}
    </div>
      
    <div class = "col-md-2"></div>  
  </div> 
{% endblock %}