lga/urls.py
from django.urls import path
from . import views

app_name = 'lga'

urlpatterns = [
    path('lgalist', views.LgaList.as_view(), name = 'lga_list'),
    path('lgacreate', views.LgaCreate.as_view(), name = 'lga_create'),
    path('lgadetail/<int:pk>/', views.LgaDetail.as_view(), name = 'lga_detail'),
    path('lgadelete/<int:pk>/', views.LgaDelete.as_view(), name = 'lga_delete'),
    path('lgaupdate/<int:pk>/', views.LgaUpdate.as_view(), name = 'lga_update')
]

pmp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('mda.urls')),
    path('', include('lga.urls')),
    path('', include('project.urls')),
    path('', include('pwa.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # USER URLS
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('change-password', views.change_password, name='change_password'),

    # ADHOC USERS URLS
    path('users/', views.user_list, name='user_list'),
    path('users/<int:id>/details/', views.user_details, name='user_details'),
    path('users/<int:id>/edit/', views.user_edit, name='user_edit'),
    path('users/addministryuser/', views.ministryuser_add, name='ministryuser_add'),
    path('users/addgovernor', views.governor_add, name='governor_add'),
    path('users/addpmp', views.pmp_add, name='pmp_add'),
    path('users/add-budget-user/', views.budget_add, name='budget_user_add'),
    path('users/add-due-process/', views.due_process_add, name='due_process_add'),
    path('users/<int:id>/delete/', views.user_delete, name='user_delete'),

    # service worker


]

users/forms.py
from django.db import transaction
from django.contrib.auth.forms import UserCreationForm
from mda.models import Ministry
from users.models import Profile
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model
User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone')


# MINISTRY USER FORM
class MinistryUserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        }
    ))

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }
    ))

    ministry = forms.ModelChoiceField(queryset=Ministry.objects.all(), required=True, widget=forms.Select(
        attrs={
            'class': 'form-control',
        }
    ))

    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password'
        }
    ))

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username', 'gender', 'ministry', 'password']

    @transaction.atomic
    def save(self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.is_ministryuser = True
        u.set_password(password)
        u.save()
        return u


# GOVERNOR FORM
class GovernorForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        }
    ))

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }
    ))

    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password'
        }
    ))

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username', 'gender', 'password']

    @transaction.atomic
    def save(self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.is_governor = True
        u.set_password(password)
        u.save()
        return u


# Budget & econ FORM
class BudgetForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        }
    ))

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }
    ))

    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password'
        }
    ))

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username', 'gender', 'password']

    @transaction.atomic
    def save(self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.is_budget = True
        u.set_password(password)
        u.save()
        return u


# Due process FORM
class DueProcessForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        }
    ))

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }
    ))

    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password'
        }
    ))

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username', 'gender', 'password']

    @transaction.atomic
    def save(self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.is_dueprocess = True
        u.set_password(password)
        u.save()
        return u


# PMP form
class PMPForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        }
    ))

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        }
    ))

    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password'
        }
    ))

    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'username', 'gender', 'password']

    @transaction.atomic
    def save(self):
        password = self.cleaned_data.pop('password')
        u = super().save()
        u.is_pmp = True
        u.set_password(password)
        u.save()
        return u


# USER EDIT PROFILE FORM
class EditProfileForm(UserChangeForm):

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
        }
    ))

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))

    password = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = User
        fields = (
            # 'username',
            'email',
            'first_name',
            'last_name',
            'gender',
            'password'
        )

users/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from users.forms import (
    MinistryUserForm,
    GovernorForm,
    PMPForm,
    BudgetForm,
    DueProcessForm,
    EditProfileForm
)
from users.models import Profile
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views import generic
from .forms import CustomUserCreationForm, CustomUserChangeForm
User = get_user_model()


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


@login_required
def profile(request):
    args = {'user': request.user}
    return render(request, 'registration/profile.html')


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'registration/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            update_session_auth_hash(request, form.user)
            form.save()
            return redirect('login')
        else:
            return redirect('change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'registration/change_password.html', args)


@login_required
def user_list(request):
    context = {}
    context['users'] = User.objects.all().order_by('-created')
    context['title'] = 'Users'
    return render(request, 'users/index.html', context)


@login_required
def user_details(request, id=None):
    context = {}
    context['user'] = get_object_or_404(User, id=id)
    return render(request, 'users/details.html', context)


# ministry user add
@login_required
def ministryuser_add(request):
    context = {}
    if request.method == 'POST':
        user_form = MinistryUserForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = MinistryUserForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)

# GOVERNOR ADD
@login_required
def governor_add(request):
    context = {}
    if request.method == 'POST':
        user_form = GovernorForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = GovernorForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


# PMP ADD
@login_required
def pmp_add(request):
    context = {}
    if request.method == 'POST':
        user_form = PMPForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = PMPForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


# Budget & eco planning ADD
@login_required
def budget_add(request):
    context = {}
    if request.method == 'POST':
        user_form = BudgetForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = BudgetForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


# due process ADD
@login_required
def due_process_add(request):
    context = {}
    if request.method == 'POST':
        user_form = DueProcessForm(request.POST, request.FILES)
        context['user_form'] = user_form
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/add.html', context)
    else:
        user_form = DueProcessForm()
        context['user_form'] = user_form
        return render(request, 'users/add.html', context)


@login_required
def user_edit(request, id=None):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        user_form = MinistryUserForm(
            request.POST, request.FILES, instance=user)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
        else:
            return render(request, 'users/edit.html', {'user_form': user_form})
    else:
        user_form = MinistryUserForm(instance=user)
        return render(request, 'users/edit.html', {'user_form': user_form})


@login_required
def user_delete(request, id=None):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        user.delete()
        return HttpResponseRedirect(reverse('users:user_list'))
    else:
        context = {}
        context['user'] = user
        return render(request, 'users/delete.html', context)

users/templates/users/add.html
{% extends "base.html" %} {% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4><strong>Add New user</strong></h4>
        </div>
        <div class="panel-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{user_form.as_p}}
                </table>
                <br>
                <input type="submit" class="btn btn-primary btn-lg" value="Add user">
            </form>
        </div>
    </div>
    </div>
    {% endblock %}

users/templates/users/delete.html
{% extends 'base.html' %} {% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4><strong>{{user.first_name}}&nbsp;{{user.last_name}}</strong></h4>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete this User?</p>
                <input type="submit" class="btn btn-danger btn-lg" value="Delete">
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/edit.html
{% extends 'base.html' %} {% block content %}
<div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4><strong>Edit User Details</strong></h4>
        </div>
        <div class="panel-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{user_form.as_p}}
                </table>
                <br>
                <input type="submit" class="btn btn-primary btn-lg" value="Update User">
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/index.html
{% extends 'base.html' %} {% block content%}
<div class="col-sm-12 col-md-8 col-md-offset-2">
    <div class="panel panel-inverse">
        <div class="panel-body">


<div class="dropdown">
<button onclick="myFunction()" class="dropbtn btn btn-default">Add New</button>
  <div id="myDropdown" class="dropdown-content">
     <a class="btn btn-primary" href="{% url 'users:ministryuser_add' %}" role="button">Ministry User</a>
     <a class="btn btn-primary" href="{% url 'users:due_process_add' %}" role="button">Due Process</a>
     <a class="btn btn-primary" href="{% url 'users:budget_user_add' %}" role="button">Budget</a>
     <a class="btn btn-primary" href="{% url 'users:governor_add' %}" role="button">Governor</a>
     <a class="btn btn-primary" href="{% url 'users:pmp_add' %}" role="button">PMP</a>
  </div>
</div>
        </div>
        </div>
        <div class = "panel panel-inverse">
        <div class="panel-heading">
            <h4><b>List of Users</b></h4>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-condensed" id="table_id">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Username</th>
                            <th>User Group</th>
                            <th>Ministry</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    {% if users %}
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td> {{user.first_name}}&nbsp;{{user.last_name}}</td>
                            <td>{{user.username}}</td>
                            <td>{{user.user_type}}</td>
                            {% if user.ministry %}
                            <td>{{user.ministry}}</td>
                            {% else %}
                            <td>-</td>
                            {% endif %}
                            <td><a href="{% url 'users:user_edit' user.id %}">Edit</a></td>
                            <td><a href="{% url 'users:user_delete' user.id %}">Delete</a></td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
        </div>
        </div>
    </div>
    </div>
    {% else %}
    <p>There is no users Available</p>
    {% endif %} 
    
    
    <script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
    {% endblock %}